apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

commonLabels:
  deployment: backend

resources:
  - backend.deployment.yaml
  - backend.service.yaml
  - app.ingress.yaml
  - backend.configmap.yaml
  - backend.secret.yaml
  - frontend.deployment.yaml
  - frontend.service.yaml
  - frontend.configmap.yaml
